USE [Allocate7]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS( SELECT 1 FROM sys.columns 
			WHERE Name  IN ('SPTeamID') AND Object_ID = Object_ID(N'[dbo].[ScheduledPersonTeam_LINK]'))
 BEGIN

	ALTER TABLE ScheduledPersonTeam_LINK ADD SPTeamID INT IDENTITY(1,1) NOT NULL PRIMARY KEY 

 END