USE [Allocate7]
GO

create OR ALTER view vAllocations_Jobs
as
 SELECT AllocateInstanceID,
		DepartmentID,
		AllocationID,
		AllocateJobID,
		StaffNumber,
		WeekNumber,
		iDay,
		Programme,
		Contact,
		Location,
		JobName,
		StartTime,
		EndTime,
		JobBackColour,
		JobFontColour,
		Comments,
		MasterJobID,
		AdhocDuty,
		UnAllocated,
		ID,
		schedulingTeamId,
		SchedulingPersonID,
		isActive,
		Edited,
		isEdited,
		isPublished,
		ProgrammeId,
		Job_Info,
		aftermidnight,
		JobDefaultColour
   FROM Allocations_Jobs
 UNION
 SELECT AllocateInstanceID,
		DepartmentID,
		AllocationID,
		AllocateJobID,
		StaffNumber,
		WeekNumber,
		iDay,
		Programme,
		Contact,
		Location,
		JobName,
		StartTime,
		EndTime,
		JobBackColour,
		JobFontColour,
		Comments,
		MasterJobID,
		AdhocDuty,
		UnAllocated,
		ID,
		schedulingTeamId,
		SchedulingPersonID,
		isActive,
		Edited,
		isEdited,
		isPublished,
		ProgrammeId,
		Job_Info,
		aftermidnight,
		JobDefaultColour	
   FROM	Allocations_Jobs_Archive