USE [Allocate7]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

USE [Allocate7]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE OR ALTER  VIEW vAllocations
as
 select AllocationID,
		AL.ID AS ID,
		OrigAllocationID,
		StaffNumber,
		DutyName,
		Duration,
		WeekNumber,
		iDay,
		StartTime,
		EndTime,
		ActingGrade,
		SortCode,
		LeaveID,
		ManualERR,
		DutyComments,
		PersonComments,
		BaseCode,
		BackColour,
		FontColour,
		AdhocDuty,
		MarkedOvertime,
		MarkedPTExtraDay,
		MarkedCompLeave,
		MarkedSickness,
		ManualOTAmount,
		ManualOTExcBreaksAmount,
		UnAllocated,
		SchedulingTeamId,
		SchedulingPersonID,
		DutyDate,
		StartDate,
		EndDate,
		IsHomeTeam,
		MarkWiad,
		MarkActual,
		aftermidnight,
		isAttention,
		isRequest,
		dutyProgramId,
		dutyProgramId2,
		dutyProgramId3,
		dutyProgramId4,
		dutyProgramId5,
		dutyProgramId6,
		dutyBreakTime,
		dutyColorId,
		MannualOThours,
		isEdited,
		MasterDutyId,
		isActive,
		isActiveDuty,
		isEditable,
		DutyTeamID,
		PlannedDuration,
		MarkOverTwelve,
		OverTwelveHrs,
		IsOverseasOverTwelve,
		IsUnderElevenBreak,
		CalculatedUnderElevenHrs,
		IsUnderElevenBreakOverride,
		OverrideUnderElevenHrs,
		UnderElevenComment,
		LeaveStartTime,
		LeaveEndTime,
		CreatedBy,
		CreatedDate,
		UpdatedBy,
		UpdatedDate
  from  Allocations AL 
  WHERE NOT EXISTS ( select 1 from ArchivedWeeks AW WHERE AW.WeekNumber = AL.WeekNumber) 
union
select  AllocationID,
		ALA.ID AS ID,
		OrigAllocationID,
		StaffNumber,
		DutyName,
		Duration,
		WeekNumber,
		iDay,
		StartTime,
		EndTime,
		ActingGrade,
		SortCode,
		LeaveID,
		ManualERR,
		DutyComments,
		PersonComments,
		BaseCode,
		BackColour,
		FontColour,
		AdhocDuty,
		MarkedOvertime,
		MarkedPTExtraDay,
		MarkedCompLeave,
		MarkedSickness,
		ManualOTAmount,
		ManualOTExcBreaksAmount,
		UnAllocated,
		SchedulingTeamId,
		SchedulingPersonID,
		DutyDate,
		StartDate,
		EndDate,
		IsHomeTeam,
		MarkWiad,
		MarkActual,
		aftermidnight,
		isAttention,
		isRequest,
		dutyProgramId,
		dutyProgramId2,
		dutyProgramId3,
		dutyProgramId4,
		dutyProgramId5,
		dutyProgramId6,
		dutyBreakTime,
		dutyColorId,
		MannualOThours,
		isEdited,
		MasterDutyId,
		isActive,
		isActiveDuty,
		isEditable,
		DutyTeamID,
		PlannedDuration,
		MarkOverTwelve,
		OverTwelveHrs,
		IsOverseasOverTwelve,
		IsUnderElevenBreak,
		CalculatedUnderElevenHrs,
		IsUnderElevenBreakOverride,
		OverrideUnderElevenHrs,
		UnderElevenComment,
		LeaveStartTime,
		LeaveEndTime,
		CreatedBy,
		CreatedDate,
		UpdatedBy,
		UpdatedDate
  from  Allocations_Archive ALA
  WHERE EXISTS ( select 1 from ArchivedWeeks AW WHERE AW.WeekNumber = ALA.WeekNumber) 
GO