name: Run JMeter Load Test

on:
  workflow_dispatch:
#  push:
#  branches: [ "main" ]

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JMeter
      run: |
        wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xzf apache-jmeter-5.6.3.tgz
        mv apache-jmeter-5.6.3 jmeter

    - name: Run JMeter Test Plan
      run: |
        jmeter/bin/jmeter.sh \
          -n \
          -t jmeter/BookingTest.jmx \
          -l results.jtl \
          -e -o html-report

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: jmeter-results
        path: |
          results.jtl
          html-report
